/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-secondary-fixed": "#002019",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2c2f41",
        "surface-tint": "#4f44e2",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-primary-container": "#fffbff",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "surface-dim": "#d7d8f0",
        "surface-container": "var(--color-surface-container)",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#c4c0ff",
        "surface-variant": "var(--color-surface-variant)",
        "outline-variant": "var(--color-outline-variant)",
        "on-primary": "#ffffff",
        primary: "#4d41df",
        error: "#ba1a1a",
        "secondary-container": "#5ffbd6",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "primary-container": "#675df9",
        "on-primary-fixed-variant": "#3622ca",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-background": "var(--color-on-background)",
        "secondary-fixed": "#5ffbd6",
        "on-tertiary-fixed": "#120068",
        "on-surface": "var(--color-on-surface)",
        outline: "var(--color-outline)",
        secondary: "#006b58",
        "primary-fixed-dim": "#c4c0ff",
        "on-tertiary-fixed-variant": "#3b2bbc",
        "secondary-fixed-dim": "#38debb",
        "tertiary-fixed-dim": "#c4c0ff",
        "surface-bright": "#fbf8ff",
        background: "var(--color-background)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-secondary-fixed-variant": "#005142",
        "on-secondary-container": "#00725e",
        "inverse-on-surface": "#f0efff",
        surface: "var(--color-surface)",
        "on-primary-fixed": "#100069",
        tertiary: "#5145d2",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#e3dfff",
        "tertiary-container": "#6a61ec",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-tertiary-container": "#fffbff",
        "priority-critical": "#dc2626",
        "priority-high": "#f43f5e",
        "priority-medium": "#f59e0b",
        "priority-low": "#3b82f6",
        "status-todo": "#3B82F6",
        "status-in-progress": "#F59E0B",
        "status-completed": "#10B981",
        "status-cancelled": "#EF4444",
      },
      fontFamily: {
        headline: ["Inter_700Bold"],
        body: ["Inter_400Regular"],
        label: ["Inter_500Medium"],
        "body-semibold": ["Inter_600SemiBold"],
        "display-black": ["Inter_900Black"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
    },
  },
  plugins: [],
};
