// Tokens live in CSS vars (dark mode mixes rgba), so opacity modifiers like
// `border-outline-variant/40` go through color-mix instead of <alpha-value>.
const token = (name) => ({ opacityValue }) =>
  opacityValue === undefined || String(opacityValue).startsWith("var(")
    ? `var(${name})`
    : `color-mix(in srgb, var(${name}) calc(${opacityValue} * 100%), transparent)`;

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: token("--color-background"),
        surface: token("--color-surface"),
        "surface-dim": token("--color-surface-dim"),
        "surface-bright": token("--color-surface-bright"),
        "surface-container-lowest": token("--color-surface-container-lowest"),
        "surface-container-low": token("--color-surface-container-low"),
        "surface-container": token("--color-surface-container"),
        "surface-container-high": token("--color-surface-container-high"),
        "surface-container-highest": token("--color-surface-container-highest"),
        "surface-variant": token("--color-surface-variant"),
        "on-surface": token("--color-on-surface"),
        "on-surface-variant": token("--color-on-surface-variant"),
        "on-background": token("--color-on-background"),
        "inverse-surface": token("--color-inverse-surface"),
        "inverse-on-surface": token("--color-inverse-on-surface"),
        outline: token("--color-outline"),
        "outline-variant": token("--color-outline-variant"),
        "surface-tint": token("--color-surface-tint"),
        primary: token("--color-primary"),
        "on-primary": token("--color-on-primary"),
        "primary-container": token("--color-primary"),
        accent: token("--color-accent"),
        "on-primary-container": "#d4d0ff",
        "inverse-primary": "#c3c0ff",
        secondary: "#b90538",
        "on-secondary": "#ffffff",
        "secondary-container": "#dc2c4f",
        "on-secondary-container": "#fffbff",
        tertiary: "#792c00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#a03c00",
        "on-tertiary-container": "#ffc9b4",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": token("--color-primary-fixed"),
        "primary-fixed-dim": token("--color-primary-fixed-dim"),
        "on-primary-fixed": "#100069",
        "on-primary-fixed-variant": "#3623ca",
        "secondary-fixed": "#ffdadb",
        "secondary-fixed-dim": "#ffb2b7",
        "on-secondary-fixed": "#40000d",
        "on-secondary-fixed-variant": "#92002a",
        "tertiary-fixed": "#ffdbcd",
        "tertiary-fixed-dim": "#ffb596",
        "on-tertiary-fixed": "#360f00",
        "on-tertiary-fixed-variant": "#7d2d00",
        "priority-critical": "#C0392B",
        "priority-high": "#C0392B",
        "priority-medium": "#B7770D",
        "priority-low": "#6B6965",
        "ai-proposed": "#5B4EE0",
        success: "#2E7D52",
        "status-todo": "#6B6965",
        "status-in-progress": "#B7770D",
        "status-completed": "#2E7D52",
        "status-cancelled": "#C0392B",
        action: token("--color-action"),
        "on-action": token("--color-on-action"),
        sidebar: token("--color-sidebar"),
        hover: token("--color-hover"),
        active: token("--color-active"),
        "text-tertiary": token("--color-text-tertiary"),
        "text-muted": token("--color-text-muted"),
        "border-subtle": token("--color-border-subtle"),
        "priority-high-text": "#C0392B",
        "priority-medium-text": "#B7770D",
        "ai-text": "#5B4EE0",
        "done-text": "#2E7D52",
        brand: {
          paper: token("--color-brand-paper"),
          surface: token("--color-brand-surface"),
          ink: token("--color-brand-ink"),
          muted: token("--color-brand-muted"),
          line: token("--color-brand-line"),
          "line-soft": token("--color-brand-line-soft"),
          field: token("--color-brand-field"),
          accent: token("--color-brand-accent"),
          "on-accent": token("--color-brand-on-accent"),
          "accent-text": token("--color-brand-accent-text"),
          "accent-soft": token("--color-brand-accent-soft"),
          proposal: token("--color-brand-proposal"),
          "proposal-edge": token("--color-brand-proposal-edge"),
          "proposal-text": token("--color-brand-proposal-text"),
          now: token("--color-brand-now"),
          success: token("--color-brand-success"),
          error: token("--color-brand-error"),
          "error-soft": token("--color-brand-error-soft"),
        },
      },
      fontFamily: {
        // Arena: UI stays system/Inter, never heavy. Active/buttons = medium (500).
        display: ["Playfair Display", "Georgia", "serif"],
        headline: ["Inter_500Medium"],
        body: ["Inter_400Regular"],
        label: ["Inter_500Medium"],
        "body-semibold": ["Inter_500Medium"],
        "display-black": ["Playfair Display", "Georgia", "serif"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em" },
        ],
        "headline-md": ["24px", { lineHeight: "32px" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px" }],
        "title-lg": ["20px", { lineHeight: "28px" }],
        "body-lg": ["16px", { lineHeight: "24px" }],
        "body-md": ["14px", { lineHeight: "20px" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em" }],
      },
      borderRadius: {
        // Arena: very small radii. Nothing above 10px except the input bar (rounded-input).
        none: "0",
        DEFAULT: "6px",
        sm: "4px",
        md: "6px",
        lg: "8px",
        xl: "8px",
        "2xl": "10px",
        "3xl": "10px",
        input: "10px",
      },
      spacing: {
        sidebar: "256px",
        gutter: "1.5rem",
        "margin-mobile": "1rem",
        "margin-desktop": "2.5rem",
        "stack-gap": "1rem",
        "section-gap": "2rem",
      },
      boxShadow: {
        card: "none",
        "card-dark": "none",
        // Modern-SaaS depth — kept scoped to board + modals so the rest of the
        // Arena surfaces stay flat. Multi-layer, very subtle resting shadow.
        kanban:
          "0 1px 2px rgba(16,24,40,0.04), 0 1px 3px rgba(16,24,40,0.07)",
        "kanban-hover":
          "0 6px 16px rgba(16,24,40,0.10), 0 2px 6px rgba(16,24,40,0.06)",
        "kanban-drag":
          "0 16px 32px rgba(16,24,40,0.18), 0 4px 8px rgba(16,24,40,0.10)",
        modal: "0 24px 60px -16px rgba(16,24,40,0.30)",
      },
    },
  },
  plugins: [],
};
