/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "var(--color-background)",
        surface: "var(--color-surface)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-variant": "var(--color-surface-variant)",
        "on-surface": "var(--color-on-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-background": "var(--color-on-background)",
        "inverse-surface": "var(--color-inverse-surface)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        outline: "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-tint": "var(--color-surface-tint)",
        primary: "var(--color-primary)",
        "on-primary": "var(--color-on-primary)",
        "primary-container": "var(--color-primary)",
        accent: "var(--color-accent)",
        "on-primary-container": "#d4d0ff",
        "inverse-primary": "#c3c0ff",
        secondary: "#b90538",
        "on-secondary": "#ffffff",
        "secondary-container": "#dc2c4f",
        "on-secondary-container": "#fffbff",
        tertiary: "#792c00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#a03c00",
        "on-tertiary-container": "#ffc9b4",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "var(--color-primary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-primary-fixed": "#100069",
        "on-primary-fixed-variant": "#3623ca",
        "secondary-fixed": "#ffdadb",
        "secondary-fixed-dim": "#ffb2b7",
        "on-secondary-fixed": "#40000d",
        "on-secondary-fixed-variant": "#92002a",
        "tertiary-fixed": "#ffdbcd",
        "tertiary-fixed-dim": "#ffb596",
        "on-tertiary-fixed": "#360f00",
        "on-tertiary-fixed-variant": "#7d2d00",
        "priority-critical": "#DC2626",
        "priority-high": "#F43F5E",
        "priority-medium": "#F59E0B",
        "priority-low": "#3B82F6",
        "ai-proposed": "#FBBF24",
        success: "#10B981",
        "status-todo": "#3B82F6",
        "status-in-progress": "#F59E0B",
        "status-completed": "#10B981",
        "status-cancelled": "#EF4444",
        action: "var(--color-action)",
        "on-action": "var(--color-on-action)",
      },
      fontFamily: {
        headline: ["Inter_700Bold"],
        body: ["Inter_400Regular"],
        label: ["Inter_500Medium"],
        "body-semibold": ["Inter_600SemiBold"],
        "display-black": ["Inter_900Black"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em" }],
        "headline-md": ["24px", { lineHeight: "32px" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px" }],
        "title-lg": ["20px", { lineHeight: "28px" }],
        "body-lg": ["16px", { lineHeight: "24px" }],
        "body-md": ["14px", { lineHeight: "20px" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em" }],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      spacing: {
        sidebar: "256px",
        gutter: "1.5rem",
        "margin-mobile": "1rem",
        "margin-desktop": "2.5rem",
        "stack-gap": "1rem",
        "section-gap": "2rem",
      },
      boxShadow: {
        card: "0 4px 20px rgba(0, 0, 0, 0.04)",
        "card-dark": "0 4px 20px rgba(0, 0, 0, 0.25)",
      },
    },
  },
  plugins: [],
};
